# Site settings
title: Atlas Development Environment
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/atlas-tester" # the subpath of your site, e.g. /blog/
url: "http://scottnath.github.io/atlas" # the base hostname & protocol for your site
collections:
  architecture:
    output: true
  flow:
    output: true
exclude: [vendor]
github: scottnath/atlas

# Build settings
markdown: kramdown
